apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-sip2.fullname" . }}-tenants
  labels:
    {{- include "edge-sip2.labels" . | nindent 4 }}
data:
  sip2-tenants.conf: {{ .Values.sip2TenantsConfig | toJson }}
