apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-inn-reach.fullname" . }}
  labels:
    {{- include "edge-inn-reach.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "edge-inn-reach.selectorLabels" . | nindent 4 }}
