apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-sftp.fullname" . }}
  labels:
    {{- include "edge-sftp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "edge-sftp.selectorLabels" . | nindent 4 }}
