apiVersion: v1
kind: Service
metadata:
  name: {{ include "mod-configuration.fullname" . }}
  labels:
    {{- include "mod-configuration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}
  selector:
    {{- include "mod-configuration.selectorLabels" . | nindent 4 }}
