apiVersion: v1
kind: Service
metadata:
  name: {{ include "okapi.fullname" . }}
  labels:
    {{- include "okapi.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
    {{- if .Values.hazelcast.enabled }}
    - port: 5701
      name: hazelcast-5701
      protocol: TCP
    - port: 5704
      name: hazelcast-5704
      protocol: TCP
    - port: 54327
      name: multicast
      protocol: TCP
    {{- end }}
  selector:
    {{- include "okapi.selectorLabels" . | nindent 4 }}
