name: Release
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
          
      - name: Helm Lint
        run: helm lint $(ls -1 | grep -v -e terraform -e charts -e package_all.sh -e docker -e index.yaml -e README.md -e release.sh -e index.html)

      - name: Release Helm Repo on Pages
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./release.sh
